version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: rest
    container_name: rest-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - rest

  db:
    image: mysql:5.7
    container_name: rest-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: rest
      MYSQL_ROOT_PASSWORD: rest
      MYSQL_PASSWORD: root
      MYSQL_USER: 
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - rest

  nginx:
    image: nginx:alpine
    container_name: rest-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - rest

networks:
  rest:
    driver: bridge
